//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctms_pm_task
    {
        public string TASKID { get; set; }
        public string PROJECTID { get; set; }
        public string PRETASKID { get; set; }
        public string FATHERTASKID { get; set; }
        public Nullable<int> ORDERNUMBER { get; set; }
        public string TASKNAME { get; set; }
        public string COSTTIME { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public string USERNAME { get; set; }
        public string PROGRESS { get; set; }
        public string TASKREMARK { get; set; }
        public string OWENRID { get; set; }
        public string OWNERPOSTID { get; set; }
        public string OWNERDEPARTMENTID { get; set; }
        public string OWNERCOMPANYID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CREATEUSER { get; set; }
        public Nullable<System.DateTime> EDITTIME { get; set; }
        public string EDITUSER { get; set; }
        public string PMANAGER { get; set; }
        public string ISCOMFIRM { get; set; }
        public Nullable<System.DateTime> REALFINISHDATE { get; set; }
    }
}
