//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctms_hr_post
    {
        public string POSTID { get; set; }
        public string POSTCODE { get; set; }
        public string POSTNAME { get; set; }
        public string COMPANYID { get; set; }
        public string DEPARTMENTID { get; set; }
        public string DEPARTMENTNAME { get; set; }
        public string POSTFUNCTION { get; set; }
        public Nullable<int> POSTNUMBER { get; set; }
        public Nullable<decimal> POSTLEVEL { get; set; }
        public string POSTCOEFFICIENT { get; set; }
        public string POSTGOAL { get; set; }
        public string FATHERPOSTID { get; set; }
        public Nullable<int> UNDERNUMBER { get; set; }
        public string PROMOTEDIRECTION { get; set; }
        public string CHANGEPOST { get; set; }
        public string CHECKSTATE { get; set; }
        public string EDITSTATE { get; set; }
        public string CREATEUSERID { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string UPDATEUSERID { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string OWNERID { get; set; }
        public string OWNERPOSTID { get; set; }
        public string OWNERDEPARTMENTID { get; set; }
        public string OWNERCOMPANYID { get; set; }
    }
}
