//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctms_sys_sysmonitor
    {
        public string OPERATEID { get; set; }
        public string USERID { get; set; }
        public string USERNAME { get; set; }
        public string OPRATESOURCE { get; set; }
        public string MODELCODE { get; set; }
        public string MODELNAME { get; set; }
        public string OPERATETYPE { get; set; }
        public string OPERATENAME { get; set; }
        public Nullable<System.DateTime> OPERATETIME { get; set; }
        public string REMARK { get; set; }
        public string OWNERID { get; set; }
        public string OWNERPOSTID { get; set; }
        public string OWNERDEPARTMENTID { get; set; }
        public string OWNERCOMPANYID { get; set; }
    }
}
