//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctms_sys_rolefunction
    {
        public string ROLEFUNCTIONID { get; set; }
        public string ROLEID { get; set; }
        public string FUNCTIONID { get; set; }
        public Nullable<decimal> PERMISSIONVALUE { get; set; }
        public string DATARANGE { get; set; }
        public string ISSETORG { get; set; }
        public string REMARK { get; set; }
        public string CREATEUSERID { get; set; }
        public string CREATEUSERNAME { get; set; }
        public Nullable<System.DateTime> CREATEDATETIME { get; set; }
        public string EDITUSERID { get; set; }
        public string EDITUSERNAME { get; set; }
        public Nullable<System.DateTime> EDITDATETIME { get; set; }
        public string OWNERID { get; set; }
        public string OWNERNAME { get; set; }
        public Nullable<decimal> ISDELETED { get; set; }
    }
}
