//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctms_hr_userpost
    {
        public string EMPLOYEEPOSTID { get; set; }
        public string ISAGENCY { get; set; }
        public string USERID { get; set; }
        public string USERNAME { get; set; }
        public string COMPANYID { get; set; }
        public string DEPARTMENTID { get; set; }
        public string POSTID { get; set; }
        public string CNAME { get; set; }
        public string DEPARTMENTNAME { get; set; }
        public string POSTNAME { get; set; }
        public Nullable<decimal> POSTLEVEL { get; set; }
        public string CHECKSTATE { get; set; }
        public string EDITSTATE { get; set; }
        public string CREATEUSERID { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string UPDATEUSERID { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
    }
}
