//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctms_sys_entitymenu
    {
        public string FUNCTIONID { get; set; }
        public string ENTITYCODE { get; set; }
        public string ENTITYNAME { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<decimal> SYSTEMCATEGORY { get; set; }
        public string PARENTID { get; set; }
        public Nullable<decimal> ISMENU { get; set; }
        public string MENUCODE { get; set; }
        public string MENUNAME { get; set; }
        public string MENUICON { get; set; }
        public string MENUURL { get; set; }
        public string ISEXPAND { get; set; }
        public string HELPERTITLE { get; set; }
        public string HELPERURL { get; set; }
        public Nullable<decimal> SORT { get; set; }
        public string REMARK { get; set; }
        public Nullable<decimal> ISPUBLIC { get; set; }
        public string CREATEUSERID { get; set; }
        public string CREATEUSERNAME { get; set; }
        public Nullable<System.DateTime> CREATEDATETIME { get; set; }
        public string EDITUSERID { get; set; }
        public string EDITUSERNAME { get; set; }
        public Nullable<System.DateTime> EDITDATETIME { get; set; }
        public string OWNERID { get; set; }
        public string OWNERNAME { get; set; }
        public Nullable<decimal> ISDELETED { get; set; }
    }
}
