//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DAL.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tmpmEntities2 : DbContext
    {
        public tmpmEntities2()
            : base("name=tmpmEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ctms_hr_company> ctms_hr_company { get; set; }
        public DbSet<ctms_hr_department> ctms_hr_department { get; set; }
        public DbSet<ctms_hr_post> ctms_hr_post { get; set; }
        public DbSet<ctms_hr_userpost> ctms_hr_userpost { get; set; }
        public DbSet<ctms_pm_dotask> ctms_pm_dotask { get; set; }
        public DbSet<ctms_pm_itemconfirm> ctms_pm_itemconfirm { get; set; }
        public DbSet<ctms_pm_itemreport> ctms_pm_itemreport { get; set; }
        public DbSet<ctms_pm_project> ctms_pm_project { get; set; }
        public DbSet<ctms_pm_task> ctms_pm_task { get; set; }
        public DbSet<ctms_sys_sysmonitor> ctms_sys_sysmonitor { get; set; }
        public DbSet<ctms_sys_userinfo> ctms_sys_userinfo { get; set; }
        public DbSet<ctms_sys_entitymenu> ctms_sys_entitymenu { get; set; }
        public DbSet<ctms_sys_permission> ctms_sys_permission { get; set; }
        public DbSet<ctms_sys_role> ctms_sys_role { get; set; }
        public DbSet<ctms_sys_rolefunction> ctms_sys_rolefunction { get; set; }
    }
}
